/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as SidebarWhisperliveRouteImport } from './../routes/_sidebar/whisperlive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarWhisperliveRoute = SidebarWhisperliveRouteImport.update({
  id: '/whisperlive',
  path: '/whisperlive',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/whisperlive': typeof SidebarWhisperliveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whisperlive': typeof SidebarWhisperliveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/whisperlive': typeof SidebarWhisperliveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/whisperlive'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/whisperlive'
  id: '__root__' | '/' | '/_sidebar' | '/_sidebar/whisperlive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/whisperlive': {
      id: '/_sidebar/whisperlive'
      path: '/whisperlive'
      fullPath: '/whisperlive'
      preLoaderRoute: typeof SidebarWhisperliveRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarWhisperliveRoute: typeof SidebarWhisperliveRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarWhisperliveRoute: SidebarWhisperliveRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
